version: '3'

networks:
  backend:

services:
  icat-db:
    build: ./postgres
    hostname: icat-db.irods
    container_name: icat-db
#     restart: unless-stopped
    expose:
      - "5432"
    networks:
      - backend

  irods-server:
    build: ./irods-server
    container_name: irods-server
    hostname: irods-server.irods
#    restart: unless-stopped
    volumes:
      - /dev/urandom:/dev/random
#      - demo-irods-icat-config:/etc/irods
#      - demo-irods-icat-logs:/var/lib/irods/iRODS/server/log
    ports:
      - 1247:1247
      - 20000-20199:20000-20199
    environment:
      - IRODS_ICAT_DBSERVER=icat-db
      - IRODS_ZONE_PORT=1247
      - IRODS_ZONE_NAME=demo
      - IRODS_WEBDAV_HOST=irods-webdav
      - IRODS_RESOURCE_OL=irods-resc-ol
      - IRODS_RESOURCE_NL=irods-resc-nl
      - IRODS_CONTROLPLANE_PORT=1248
      - IRODS_DATA_PORT_RANGE_BEG=20000
      - IRODS_DATA_PORT_RANGE_END=20199
    depends_on:
      - icat-db
    links:
      - icat-db
    networks:
      - backend

  irods-webdav:
    build: ./davrods
    hostname: irods-webdav.irods
#    restart: unless-stopped
    volumes:
      - /dev/urandom:/dev/random
      - ./davrods/config:/config
    environment:
      - IRODS_ICAT_HOST=irods-icat
      - IRODS_ZONE_PORT=1247
      - IRODS_ZONE_NAME=demo
    ports:
      - 443:443
    depends_on:
      - irods-server

#volumes:
#  demo-irods-icat-config:
#    external: true
#  demo-irods-icat-logs:
#    external: true
#  demo-irods-resc-ol-config:
#    external: true
#  demo-irods-resc-ol-logs:
#    external: true
#  demo-irods-resc-ol-vault:
#    external: true
#  demo-irods-resc-nl-config:
#    external: true
#  demo-irods-resc-nl-logs:
#    external: true
#  demo-irods-resc-nl-vault:
#    external: true
#  demo-postgres-data:
#    external: true
